### ISSUE TITLE
VB.NET files support

### ISSUE THREAD

**Issue by Virenbar** [1thenikita/Visual-Studio#22]
**Is your feature request related to a problem? Please describe:**
Discord is showing icon for an unrecognized extension when editing *.vb files.

**Solution:**
Add recognition of .vb files.

**Additional context:**
[VB Icon](https://docs.microsoft.com/media/logos/logo_VB.svg)
![image](https://user-images.githubusercontent.com/10138491/90335114-b8dcad00-dfeb-11ea-8566-6c15dd4c3a72.png)

**Comment by 1thenikita** [comment]
I will do how to access an application in Discord.I will do how to access an application in Discord.
