### ISSUE TITLE
Empty timestamps after disabling "Reset timestamps on file change"

### ISSUE THREAD

**Issue by victorshx** [1thenikita/Visual-Studio#31]
**Bug description:** Timestamps becomes missing from Discord Presence when **"Reset timestamps on file change"** is disabled after time starts counting.

**Reproduction steps:**

1. Make sure **"Reset timestamps on file change"** is enabled first, edit some files and check that the time is running
2. Uncheck **"Reset timestamps on file change"** and save the settings
4. Bam! Timestamps is missing from the Discord Rich Presence

**Expected behavior:**

When disabled, shouldn't the current timestamps become the initial timestamps, keep the current timestamps, or reset the timestamps?

**Screenshots:**
![image](https://user-images.githubusercontent.com/34960876/102530667-43d5cd00-40dc-11eb-8e42-75d4b034858d.png)

**Desktop (please complete the following information):**

 - OS: Windows 10 1809 Build 17763.1637
 - Visual Studio 2019 Version 16.7.5
 - 5.3

**Additional context**

**Comment by victorshx** [comment]
@VisualDevelopment I have a fix for it, do you need me to push the PR?

**Comment by 1thenikita** [comment]
@victorshx Let me check.

**Comment by 1thenikita** [comment]
@victorshx I don't have the same bug.
Probably corrected, wait for a new version.

**Comment by victorshx** [comment]
@1thenikita Looking forward.

**Comment by ashap5** [comment]
i had it too fixed after restart

**Comment by 1thenikita** [comment]
> i had it too fixed after restart

Reinstalling discord may help as well.

The question is settled.
