### ISSUE TITLE
Idling Always being shown next to the Project/Solution Name

### ISSUE THREAD

**Issue by ScarVite** [1thenikita/Visual-Studio#47]
**Bug description:**

It's adding Idling next to my Project/ Solution name while i'm actively working on it.

**Reproduction steps:**

1. Install The Extension
2. Open a Project via a Solution (.sln file)
3. Look on Discord
4. Constantly See Idling next to the Solution/Project name

**Expected behavior:**

Idling Should only be shown, if i didn't edit anything in a while

**Screenshots:**

![DiscordCanary_BacZ85BcqD](https://user-images.githubusercontent.com/43887376/110500064-1d329b80-80f9-11eb-90dc-b7f622a3dbf8.png)

**Desktop (please complete the following information):**

 - Windows 10 Pro 20H2 19042.804
 - Microsoft Visual Studio Community 2019 Version 16.9.0
 - 5.5

**Additional context**

**Comment by Dicey95** [comment]
This bug is super annoying, I'd say just removing the "Idling" feature all-together.,

**Comment by orrburgel** [comment]
Please fix this

**Comment by 1thenikita** [comment]
Yes, this update is coming
