### ISSUE TITLE
Error message "bad exception"

### ISSUE THREAD

**Issue by YvvkiRika** [1thenikita/Visual-Studio#52]
**Bug description:**

Visual Studio 2019 Preview will show an error message saying "bad exception" when trying to close the app when there's a unsaved file while using this extension.

Visual Studio won't quit afterwards without crashing it via task manager.

**Reproduction steps:**

1. Edit any file on visual studio
2. Close the app without saving
3. See error message

**Expected behavior:**

A prompt to quit, shows unsaved file, then quit successfully.

**Screenshots:**

https://imgur.com/a/kvM4PwR

**Desktop:**

 - OS: Windows 10 Pro 20H2 Build 19042.928
 - Visual Studio Community 2019 Preview, Version 16.10.0 Preview 1.0
 - Extension Version 5.5

**Additional context**

Log: https://pastebin.com/7tAqpU3B

Fun fact, if you editing another file after the error show and going back to the unsaved file, it will freeze VS and crash it.

Thanks!

**Comment by 1thenikita** [comment]
Good afternoon! Try to update your extension to a newer version, maybe the problem will disappear.

**Comment by TheLeftExit** [comment]
Just encountered the same issue on 5.5.3.

VS would show "Fatal error 0x8000FFFF" when attempting to save a file and "Unable to access disposed object Discord IPC" when trying to change any settings through the extension's menu.

**Comment by 1thenikita** [comment]
An update is on its way! You can wait and get the update from the marketplace or download it manually [here](https://github.com/1thenikita/Visual-Studio/releases/tag/5.5.4).
