### ISSUE TITLE
Crashes after DiscordRpcClient is disposed

### ISSUE THREAD

**Issue by ryan-dawson** [1thenikita/Visual-Studio#56]
https://github.com/1thenikita/Visual-Studio/blob/bc0b604319cb34afe3c2ad397defa95ca0c31e60/DiscordRPforVSPackage.cs#L188
https://github.com/1thenikita/Visual-Studio/blob/bc0b604319cb34afe3c2ad397defa95ca0c31e60/DiscordRPforVSPackage.cs#L115

`SetPresence` and `ClearPresence` both throw ObjectDisposedException when called on a disposed instance. The exception is not handled and winds up crashing Visual Studio. Each of the lines above should be guarded by an `if (!this.Discord.IsDisposed)` check.

**Comment by 1thenikita** [comment]
An update is on its way! You can wait and get the update from the marketplace or download it manually [here](https://github.com/1thenikita/Visual-Studio/releases/tag/5.5.4).
