### ISSUE TITLE
how to change language

### ISSUE THREAD

**Issue by UnDERL1** [1thenikita/Visual-Studio#61]
"Ability to use different languages. Available languages: English and Russian."

How can I change the language from Russian to English? Because my language is automatically set to Russian, although the visual studio is in English.

**Comment by 1thenikita** [comment]
The language is set according to the language of the operating system.

**Comment by WeaselOnaStick** [comment]
![image](https://user-images.githubusercontent.com/10953814/130592106-f2436457-541b-4012-a5e0-33c712993b42.png)
I have English set as my primary language but the app forces Russian language. Please add a setting to manually change it, this is annoying

**Comment by 1thenikita** [comment]
This feature will be implemented in the next update of the extension, but in a few weeks

**Comment by TheLeftExit** [comment]
> 
> 
> "Ability to use different languages. Available languages: English and Russian."
> 
> How can I change the language from Russian to English? Because my language is automatically set to Russian, although the visual studio is in English.

You can use my fork that forces English language for the time being.
https://github.com/TheLeftExit/Visual-Studio

**Comment by 1thenikita** [comment]
Upgrade your extension and use it happily!
