### ISSUE TITLE
Discord Rich not showing in tools tab

### ISSUE THREAD

**Issue by lucasfurtado** [1thenikita/Visual-Studio#74]
The extension is working but I can't configure anymore because it isn't in my Tools tab.

![Untitled](https://user-images.githubusercontent.com/54894232/133339809-9eb860b0-22c4-4781-8b36-fef4c0308282.png)

I tried to uninstall/install the extensiona , delete all extensions files and after repair VS but still the option isn't in the tools tab.

**Comment by thediscover22450** [comment]
Same problem here

**Comment by 1thenikita** [comment]
Version VS?

**Comment by lucasfurtado** [comment]
> Version VS?

VS 2019 (community)

**Comment by JoaoRuss0** [comment]
I have the same issue, reinstalling did not help. VS 2019 Community (Version 16.11.3)

**Comment by kerohero** [comment]
same problem, VS 2019 Community

**Comment by TheLifeWorm** [comment]
Same problem, VS 2019 Preview

**Comment by 1thenikita** [comment]
Expect an update within a few hours. I apologize for this bug, now I will see how it appeared

**Comment by AnonimFan** [comment]
Same error, but okay. I will wait

**Comment by nils-kt** [comment]
Same problem. 
Microsoft Visual Studio Enterprise 2019 - Version 16.11.3

**Comment by veteri** [comment]
I have the same problem.
Microsoft Visual Studio Community 2019 Version 16.11.2

**Comment by NazimOfRivia** [comment]
Hello,
Same problem
Microsoft Visual Studio Community 2019
Version 16.11.3

**Comment by kerohero** [comment]
@1thenikita Is there is a way to edit the settings from a system file(maybe?)? a manual solution?

**Comment by Kavarera** [comment]
Same problem right here, but idk what version i use. but its vs2019

**Comment by angurishu** [comment]
Me too, please ping when there's a fix!

**Comment by 1thenikita** [comment]
Expect bug fixes within 10 minutes and more!

**Comment by 1thenikita** [comment]
🙌Congratulations🙌! Upgrade your extension and use it happily!

![image](https://user-images.githubusercontent.com/35877788/134731379-677ce218-08a6-4351-b1e5-82e5f17e5155.png)

@lucasfurtado @RaphaelBardini @JoaoRuss0 @kerohero @TheLifeWorm @AnonimFan @nils-kt @veteri @Cybermade @Kavarera @angurishu

**Comment by JoaoRuss0** [comment]
Can't update it, after I go to Extensions -> Manage Extensions -> Updates:
![image](https://user-images.githubusercontent.com/40304274/134751773-9d9cabb1-6043-4726-b322-189b2f17979c.png)

Press the "Update" button on the discord extension:
![image](https://user-images.githubusercontent.com/40304274/134751841-4e7dc476-7de4-4404-a32a-42dc3fe7897b.png)

And close all VS windows, VSIX Installer tells me "This extension is already installed for all applicable products".
![image](https://user-images.githubusercontent.com/40304274/134751758-3067cddd-a082-43d6-8591-13aff2365fb4.png)

**Comment by 1thenikita** [comment]
> Can't update it, after I go to Extensions -> Manage Extensions -> Updates:
> ![image](https://user-images.githubusercontent.com/40304274/134751773-9d9cabb1-6043-4726-b322-189b2f17979c.png)
> 
> Press the "Update" button on the discord extension:
> ![image](https://user-images.githubusercontent.com/40304274/134751841-4e7dc476-7de4-4404-a32a-42dc3fe7897b.png)
> 
> And close all VS windows, VSIX Installer tells me "This extension is already installed for all applicable products".
> ![image](https://user-images.githubusercontent.com/40304274/134751758-3067cddd-a082-43d6-8591-13aff2365fb4.png)
> 

Try removing the extension completely and installing it again.

**Comment by angurishu** [comment]
> Try removing the extension completely and installing it again.
It doesn't work, not for me at least. I've reinstalled the extension multiple times and repaired vs code and still nothing :<

**Comment by MrFranQx** [comment]
Same problem here, see also #75. Even after repairing Visual Studio it still installs verion 5.5.2, and upgrade to 5.5.3 doesn't work.

**Comment by 1thenikita** [comment]
https://github.com/1thenikita/Visual-Studio/releases

**Comment by 1thenikita** [comment]
Or try to update again, if not, then install it manually.

**Comment by Cybermade** [comment]
Working fine now, thanks !

**Comment by JoaoRuss0** [comment]
> > Can't update it, after I go to Extensions -> Manage Extensions -> Updates:
> > ![image](https://user-images.githubusercontent.com/40304274/134751773-9d9cabb1-6043-4726-b322-189b2f17979c.png)
> > Press the "Update" button on the discord extension:
> > ![image](https://user-images.githubusercontent.com/40304274/134751841-4e7dc476-7de4-4404-a32a-42dc3fe7897b.png)
> > And close all VS windows, VSIX Installer tells me "This extension is already installed for all applicable products".
> > ![image](https://user-images.githubusercontent.com/40304274/134751758-3067cddd-a082-43d6-8591-13aff2365fb4.png)
> 
> Try removing the extension completely and installing it again.

Oh I did that multiple times but always the same issue would pop up.

**Comment by JoaoRuss0** [comment]
![image](https://user-images.githubusercontent.com/40304274/134770474-11021b9b-95d1-4caf-bcb1-14cd0824ca65.png)
![image](https://user-images.githubusercontent.com/40304274/134770485-705f203f-4bad-4c05-86a0-2c5e8274d558.png)

Manual installation worked falwlessly! 😄
