### ISSUE TITLE
VSIX Installer error can't update

### ISSUE THREAD

**Issue by Kavarera** [1thenikita/Visual-Studio#75]
![image](https://user-images.githubusercontent.com/52194252/134738149-06af8305-9aa9-4559-bb2e-05087dbeb4f6.png)

This error happen when i click update on "Manage extension"

**Comment by MrFranQx** [comment]
I have the same problem, VS Community 2019 16.11.3

**Comment by angurishu** [comment]
Me too - after the extension was updated, every time I tried to update the extension there was this exact same issue.  Tried repairing VS and installing yet again and updating only to no avail - VS Community 2019 16.11.3

**Comment by 1thenikita** [comment]
It seems to me that Microsoft has taken too long to verify the code. I will now post a manual installation of the new version without a digital signature.

**Comment by 1thenikita** [comment]
Check [this](https://github.com/1thenikita/Visual-Studio/releases)

@Kavarera @MrFranQx @angurishu

**Comment by 1thenikita** [comment]
Or try to update again, if not, then install it manually.
